---
title: "OneIsland_results2017"
author: "KP"
date: "21/04/2021"
output:
  word_document:
    reference_docx: "Template_doc.docx"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
source("SmallLakesDB.R")
ls()
```

## Methods

*** Doesn't apply: The mass of individual rainbow trout and eastern brook trout measured only for fork length (`r paste0("n=",nrow(no.wt))` and `r paste0("n=",nrow(no.wt.EB))`, respectively) was predicted using the log length to mass relationship from individual fish measured for both fork length and mass (`r paste0("n=",nrow(wt))` and `r paste0("n=",nrow(wt.EB))`, respectively) and then back-transformed following Ogle (2016). 


*** Does not apply: Ages were predicted for individual fish without measured ages using a length-age key (n=`r nrow(RB.noages.lk.catch)`). However, fish smaller than `r lcat10.toosmall.current` mm were not sampled for age and therefore the age of these fish could not be predicted (n=`r n.toosmall.current`). 


Ages were predicted for individual EB from `r noquote(yr.select)` without measured ages using a length-age key (n=`r nrow(EB.noages.lk.catch)`) from individuals with length and age measured (n=`r nrow(EB.ages.lk.catch)`). For comparison, ages were predicted for individual EB from `r noquote(yr.prev)` without measured ages using a length-age key (n=`r nrow(EB.noages.lk.catch.prev)`) from individuals with length and age measured (n=`r nrow(EB.ages.lk.catch.prev)`, Ogle (2016)).




